multi_label/multi_label/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.views.static import serve
from multi_label import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pred/', include("pred.urls")),
    url(r'^uploads/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

multi_label/pred/urls.py
from django.urls import path
from pred import views

urlpatterns = [
    path("index/", views.index),
    path("register/", views.user_register),
    path("login/", views.user_login),
    path("change_passwd/", views.user_change_passwd),
    path("history_list/", views.history_list),
    path("compute/", views.compute),
    path("logout/", views.user_logout)
]

multi_label/pred/models.py
from django.db import models


# Create your models here.

class History(models.Model):
    patient_id = models.CharField(max_length=20)
    patient_name = models.CharField(max_length=20)
    img_type = models.CharField(max_length=20)
    photo = models.ImageField()
    pred_result = models.CharField(max_length=100)
    note = models.CharField(max_length=100, null=True)
    user = models.ForeignKey(to='User', on_delete=models.CASCADE)
    pred_time = models.DateTimeField(auto_now_add=True)


class User(models.Model):
    user_name = models.CharField(max_length=20)
    password = models.CharField(max_length=32)

multi_label/pred/views.py
from django.shortcuts import render, redirect
from PIL import Image
from pred import use_model, models, my_form
from functools import wraps
from django.contrib import messages


# Create your views here.


def check_login(func):
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        next_url = request.get_full_path()
        if request.session.get("user_name"):
            return func(request, *args, **kwargs)
        else:
            return redirect("/pred/login/?next={}".format(next_url))

    return wrapper


@check_login
def index(request):
    return render(request, "index.html", {"user_name": request.session.get("user_name")})


def user_register(request):
    if request.method == "POST":
        form = my_form.UserRegisterForm(request.POST)
        if form.is_valid():
            models.User.objects.create(user_name=request.POST.get('user_name'),
                                       password=my_form.getMd5Passwd(request.POST.get('password')))
            messages.info(request, "注册成功")
            return redirect("/pred/login")
        else:
            messages.error(request, form.errors['__all__'][0])
    form = my_form.UserRegisterForm()
    return render(request, "user_register.html", {'form': form})


def user_login(request):
    if request.method == "POST":
        form = my_form.UserLoginForm(request.POST)
        if form.is_valid():
            request.session['user_name'] = request.POST.get('user_name')
            messages.info(request, "登录成功")
            next_url = request.GET.get("next")
            if next_url:
                return redirect(next_url)
            else:
                return redirect("/pred/index")
        else:
            messages.error(request, form.errors['__all__'][0])
    form = my_form.UserLoginForm()
    return render(request, "user_login.html", {'form': form})


def user_logout(request):
    request.session.delete()
    messages.info(request, "注销成功")
    return redirect("/pred/login")


@check_login
def user_change_passwd(request):
    if request.method == "POST":
        form = my_form.UserChangePasswdForm(request.POST)
        if form.is_valid():
            old_passwd = request.POST.get("old_passwd")
            if my_form.getMd5Passwd(old_passwd) != models.User.objects.get(
                    user_name=request.session.get("user_name")).password:
                messages.error(request, "旧密码错误")
                return render(request, "user_change_passwd.html", {'form': form})
            new_passwd = request.POST.get("new_passwd")
            models.User.objects.filter(user_name=request.session.get("user_name")).update(
                password=my_form.getMd5Passwd(new_passwd))
            messages.info(request, "修改成功")
            return redirect("/pred/logout")
        else:
            messages.error(request, form.errors['__all__'][0])
    form = my_form.UserChangePasswdForm()
    return render(request, "user_change_passwd.html", {'form': form})


@check_login
def history_list(request):
    history_obj_list = models.History.objects.filter(
        user=models.User.objects.get(user_name=request.session.get("user_name"))).order_by("-pred_time")
    if request.method == "POST":
        patient_id = request.POST.get('patient_id')
        patient_name = request.POST.get('patient_name')
        if len(patient_id) > 0:
            history_obj_list = models.History.objects.filter(
                user=models.User.objects.get(user_name=request.session.get("user_name")),
                patient_id=patient_id).order_by("-pred_time")
        if len(patient_name) > 0:
            history_obj_list = models.History.objects.filter(
                user=models.User.objects.get(user_name=request.session.get("user_name")),
                patient_name=patient_name).order_by("-pred_time")
        if len(patient_id) > 0 and len(patient_name) > 0:
            history_obj_list = models.History.objects.filter(
                user=models.User.objects.get(user_name=request.session.get("user_name")), patient_id=patient_id,
                patient_name=patient_name).order_by("-pred_time")
        messages.info(request, "检索成功")
        return render(request, "history_list.html", {"history_obj_list": history_obj_list, "patient_id": patient_id,
                                                     "patient_name": patient_name})
    return render(request, "history_list.html", {"history_obj_list": history_obj_list})


@check_login
def compute(request):
    if request.method == "POST":
        form = my_form.UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            user = models.User.objects.get(user_name=request.session.get("user_name"))
            history = models.History(photo=request.FILES['photo'],
                                     patient_id=request.POST.get("patient_id"),
                                     patient_name=request.POST.get("patient_name"),
                                     img_type=request.POST.get("img_type"),
                                     note=request.POST.get("note"),
                                     user=user,
                                     pred_result="无"
                                     )
            history.save()
            photo = Image.open(history.photo.path)
            labels = use_model.multi_label_classify(photo, history.img_type)
            history.pred_result = labels
            history.save()
            return render(request, "compute.html", {'form': form, 'photo': history.photo, 'labels': labels})
    form = my_form.UploadImageForm()
    return render(request, "compute.html", {'form': form})

multi_label/pred/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>眼科影像病变体征识别系统</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>
</head>
<body>
<h1 class="text-center">眼科影像病变体征识别系统</h1>
{% include "nav.html" %}

{% block bar %}

{% endblock %}

{% block main%}

{% endblock %}
</body>
</html>

multi_label/pred/templates/before_base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>眼科影像病变体征识别系统</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
            integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>
    <style>
        * {
            font-size: 18px;
        }

        #before_container {
            position: relative;
            top: 15vh;
        }

        .form-control {
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
<div class="page-header">
    <h1 class="text-center">眼科影像病变体征识别系统</h1>
</div>
{% block main%}

{% endblock %}
<div style="position:fixed;bottom:0;left:50%;transform:translateX(-50%);opacity:0.5">
    <span style="font-size: 15px">@author: liguoying</span>
</div>
</body>
</html>

multi_label/pred/templates/compute.html
{% extends "base.html" %}

{% block main %}

<style>
    #id_img_type, #id_img_type li {
        display: inline;
    }

    #id_img_type li:last-child {
        margin-left: 30px;
    }

    form p:nth-of-type(3) {
        display: inline;
    }

    form p:nth-of-type(5) {
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>

<div class="col-md-10 col-md-offset-1">
    <h1 class="page-header">影像识别</h1>
    <div class="panel panel-primary">
        <div class="panel-heading">上传眼科影像并识别病变体征</div>
        <div class="panel-body">
            <div class="container-fluid">
                <div class="col-md-4">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <div class="pull-right">
                            <button type="submit" class="btn btn-primary btn-lg"><span
                            class="glyphicon glyphicon-play"></span> 识别</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-6 col-md-offset-2">
                    <div id="show_result" style="display:none">
                        <div>上传影像名称： {{photo.name}}</div>
                        <div>
                            影像预览：
                            <img src="/uploads/{{photo.name}}" , height="400" , width="400"/>
                        </div>
                        <div>识别出的体征：{{labels}}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if labels %}
<script>
    document.getElementById("show_result").style.display = "block"
</script>
{% endif %}

{% if messages %}
<script>
    {% for msg in messages %}
    alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock %}

multi_label/pred/templates/history_list.html
{% extends "base.html" %}

{% block main %}

<div class="col-md-10 col-md-offset-1">
    <h1 class="page-header">历史记录</h1>
    <div class="panel panel-primary">
        <div class="panel-heading">查看当前用户的历史识别记录</div>
        <div class="panel-body">
            <form class="form-inline" method="post">
                {% csrf_token %}
                <div class="form-group" style="width: 20%">
                    <label>患者id:</label>
                    <input type="text" style="width: 70%;margin-top: 20px" placeholder="根据患者id检索（可选）"
                           class="form-control" name="patient_id" value="{{patient_id}}">
                </div>
                <div class="form-group" style="width: 20%">
                    <label>患者姓名:</label>
                    <input type="text" style="width: 70%;margin-top: 20px" placeholder="根据患者姓名检索（可选）"
                           class="form-control" name="patient_name" value="{{patient_name}}">
                </div>
                <button type="submit" class="btn btn-primary btn-lg"><span
                        class="glyphicon glyphicon-search"></span> 检索
                </button>
            </form>
            <table class="table table-hover table-striped table-condensed"
                   style="table-layout:fixed;word-break:break-all">
                <tr class="info">
                    <th style="width: 10%">患者id</th>
                    <th style="width: 10%">患者姓名</th>
                    <th style="width: 10%">影像类别</th>
                    <th style="width: 15%">影像名称</th>
                    <th style="width: 10%">影像缩略图</th>
                    <th style="width: 15%">识别结果</th>
                    <th style="width: 15%">识别时间</th>
                    <th style="width: 15%">备注</th>
                </tr>

                <tbody>
                {% for history_obj in history_obj_list %}
                <tr>
                    <td>{{ history_obj.patient_id }}</td>
                    <td>{{ history_obj.patient_name }}</td>
                    <td>{{ history_obj.img_type }}</td>
                    <td>{{ history_obj.photo.name }}</td>
                    <td>
                        <div style="position: relative;width: 100%;padding-top: 100%">
                            <img src="/uploads/{{history_obj.photo.name}}"
                                 style="position:absolute;top:0;left:0;width:100%;height:100%" alt="影像缩略图"/>
                        </div>
                    </td>
                    <td>{{ history_obj.pred_result }}</td>
                    <td>{{ history_obj.pred_time|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ history_obj.note }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% if messages %}
<script>
    {% for msg in messages %}
    alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock %}

multi_label/pred/templates/index.html
{% extends "base.html" %}

{% block main %}

<div class="col-md-8 col-md-offset-2">
    <h1 class="page-header">首页</h1>
    <div class="jumbotron">
        <div class="container">
            <h1>Hello, {{user_name}}!</h1>
            <p>这里是基于深度学习的眼科影像病变体征识别系统，致力于利用计算机技术识别患者眼科影像中的湿性AMD病变体征，
                目前支持识别OCT影像和彩色眼底影像中的病变体征，提供交互友好的系统功能，从而辅助医生诊断治疗。
            </p>
            <p>
                本系统使用由ResNeSt50神经网络和数千张眼科影像数据集训练而成的多标签分类模型，经过在测试集上的综合评估后认为：
                该模型拥有对于OCT影像约75%的体征严格匹配准确率和80%以上的精确率、召回率、F1值，汉明损失约0.03；
                拥有对于彩色眼底影像约71%的体征严格匹配准确率和73%以上的精确率、召回率、F1值，汉明损失约0.09。
            </p>
            <p><a class="btn btn-primary btn-lg" href="/pred/compute/" role="button"><span
                    class="glyphicon glyphicon-plane"></span> 开始使用！</a></p>
        </div>
    </div>
</div>

{% if messages %}
<script>
    {% for msg in messages %}
    alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock %}

multi_label/pred/templates/nav.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="font-size: 24px;margin-top: 10px;margin-bottom: 10px;">Deep Learning</a>
        </div>

        <div id="navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/pred/index/" class="btn btn-lg"><span class="glyphicon glyphicon-home"></span> 首页</a></li>
                <li><a href="/pred/compute/" class="btn btn-lg"><span class="glyphicon glyphicon-cloud"></span> 影像识别</a>
                </li>
                <li><a href="/pred/history_list/" class="btn btn-lg"><span class="glyphicon glyphicon-record"></span>
                    历史记录</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/pred/change_passwd/" class="btn btn-lg"><span class="glyphicon glyphicon-user"></span>
                    修改密码</a></li>
                <li><a href="/pred/logout" class="btn btn-lg"><span class="glyphicon glyphicon-log-out"></span> 注销</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

multi_label/pred/templates/user_change_passwd.html
{% extends "base.html" %}

{% block main %}

<div class="col-md-4 col-md-offset-4">
    <h1 class="page-header">修改密码</h1>
    <div class="panel panel-primary">
        <div class="panel-heading">修改当前登录用户的密码</div>
        <div class="panel-body">
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <div class="pull-right">
                    <button type="submit" class="btn btn-primary btn-lg"><span
                            class="glyphicon glyphicon-wrench"></span> 修改
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% if messages %}
<script>
    {% for msg in messages %}
    alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock %}

multi_label/pred/templates/user_login.html
{% extends "before_base.html" %}

{% block main %}

<div id="before_container" class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-primary">
            <div class="panel-heading">登录</div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="col-md-8 col-md-offset-2">
                        <button type="submit" class="btn btn-primary pull-left" style="font-size: 18px"><span
                                class="glyphicon glyphicon-log-in"></span> 登录
                        </button>
                        <button class="btn btn-link pull-right"><a href="/pred/register/">没有账号？去注册</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% if messages %}
<script>
    {% for msg in messages %}
    alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock %}

multi_label/pred/templates/user_register.html
{% extends "before_base.html" %}

{% block main %}

<div id="before_container" class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-primary">
            <div class="panel-heading">注册</div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="col-md-8 col-md-offset-2">
                        <button type="submit" class="btn btn-primary pull-left" style="font-size: 18px"><span
                                class="glyphicon glyphicon-check"></span> 注册
                        </button>
                        <button class="btn btn-link pull-right"><a href="/pred/login/">已有账号？去登录</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% if messages %}
<script>
    {% for msg in messages %}
    alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

{% endblock %}